#!/bin/bash
# sudo ./cyberpptp --add amr 
# sudo ./cyberpptp --delete amr

if [ "`whoami`" != "root" ]
then
	echo "You must be root to start logger_ingest."
	exit 1
fi

ACTION=$1
TUNNEL=$2
SERVER=$3
USERNAME=$4
PASSWORD=$5

PPTPSETUP_BIN="/usr/sbin/pptpsetup"
ROUTE_BIN="/sbin/route"

cur_interface=`route | awk '/default/ { print $NF }'`

CheckIfTunnelExist () {
  if [ ! -f "/etc/ppp/peers/$TUNNEL" ]
  then
    echo -e "No Tunnel named $TUNNEL exists\nNothing to delete.\n"
    exit 1
  fi
}

CreateRoutesFile () {
if [[ "com" == *"$SERVER"* ]]; then
    ip="-host $SERVER"
else
    ip="$SERVER"
fi

F_PATH=/etc/ppp/ip-up.d/"$TUNNEL"
echo "#!/bin/sh" > $F_PATH
echo "route del default $cur_interface" >> $F_PATH
echo "route add default dev ppp0" >> $F_PATH
#echo "route add $ip dev $cur_interface" >> $F_PATH
#echo "route del -net $SERVER gw 0.0.0.0 netmask 255.255.255.255 dev $cur_interface" >> $F_PATH
chmod +x $F_PATH

F_PATH=/etc/ppp/ip-down.d/"$TUNNEL"
echo "#!/bin/sh" > $F_PATH
echo "route del default ppp0" >> $F_PATH
echo "route add default dev $cur_interface" >> $F_PATH
chmod +x $F_PATH
}

CreatePeersFile () {
F_PATH=/etc/ppp/peers/"$TUNNEL"
echo "lock" > $F_PATH
echo "noauth" >> $F_PATH
echo "nobsdcomp" >> $F_PATH
echo "nodeflate" >> $F_PATH
echo "pty \"pptp $SERVER --nolaunchpppd\"" >> $F_PATH
echo "name $USERNAME" >> $F_PATH
echo "remotename PPTP" >> $F_PATH
echo "require-mppe-128" >> $F_PATH
echo "file /etc/ppp/options.pptp" >> $F_PATH
echo "ipparam tunnel" >> $F_PATH
}


add () {
CreatePeersFile && CreateRoutesFile
echo "$USERNAME PPTP $PASSWORD *" >> /etc/ppp/chap-secrets
pon $TUNNEL 
echo "nameserver 8.8.8.8" >> /etc/resolv.conf
echo "Connecting..."
sleep 15
/etc/ppp/ip-up.d/"$TUNNEL"
}

delete () {
CheckIfTunnelExist
/etc/ppp/ip-down.d/"$TUNNEL"
# $PPTPSETUP_BIN --delete $TUNNEL
rm "/etc/ppp/ip-up.d/$TUNNEL"
rm "/etc/ppp/ip-down.d/$TUNNEL"
rm "/etc/ppp/peers/$TUNNEL"
poff $TUNNEL
sed -i 's/.*8.8.8.8.*//' /etc/resolv.conf
service network-manager restart
}

case "$ACTION" in
  "--delete")
    delete
    ;;

  "--add")
    add
    ;;
  *)
    ;;
esac
